### PR TITLE
Introduces README documentation for importing Vireo (Thesis Central) submissions into DataSpace

### PR DESCRIPTION
**Pull request by jrgriffiniii**
This also includes and improves upon several `tcsh` scripts.

### CODE REVIEW

**Review by kmcelwee — APPROVED** [review]
Wow, this is great! Looking forward to talking about this later today

**Review by kmcelwee — APPROVED** [review]

**Comment by kmcelwee** [comment]
whoops, ignore me!

**Comment by jrgriffiniii** [comment]
`enhanceAips.py` yields the following error:

ERROR:root:export/English/RestrictionsWithId.xlsx does not contain a 'Submitted By' column

As the Excel Spreadsheet seems to be completely stripped of columns once parsed by this script.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/dspace-python/blob/master/thesiscentral-vireo/dataspace/python/vireo.py#L82 is the line which is problematic for me locally.

**Comment by jrgriffiniii** [comment]
This needs to be rebased and updated. Closing with the hope to using another branch.

**Pull request closed without merging**
